enum ActionType {
  GET_ALL_EDUCATIONS = 'GET_ALL_EDUCATIONS',
  CREATE_EDUCATION = 'CREATE_EDUCATION',
  UPDATE_EDUCATION = 'UPDATE_EDUCATION',
  REMOVE_EDUCATION = 'REMOVE_EDUCATION',
}

export { ActionType };
