enum ActionType {
  SET_USER = 'SET_USER',
  GET_USER = 'GET_USER',
  REMOVE_USER = 'REMOVE_USER',
  LOGIN_USER = 'LOGIN_USER',
  SIGN_UP_USER = 'SIGN_UP_USER',
  LOGOUT_USER = 'LOGOUT_USER',
  UPDATE_COMPANY = 'UPDATE_COMPANY',
}

export { ActionType };
