const EducationValidationRule = {
  SPECIALIZATION_MIN_LENGTH: 2,
  SPECIALIZATION_MAX_LENGTH: 30,
  UNIVERSITY_MIN_LENGTH: 2,
  UNIVERSITY_MAX_LENGTH: 50,
  DEGREE_MIN_LENGTH: 2,
  DEGREE_MAX_LENGTH: 30,
};

export { EducationValidationRule };
