const StepsValidationRule = {
  POSITION_MIN_LENGTH: 2,
  POSITION_MAX_LENGTH: 30,
  EXPERIENCE_MIN_LENGTH: 10,
  EXPERIENCE_MAX_LENGTH: 100,
  EDUCATION_MIN_LENGTH: 10,
  EDUCATION_MAX_LENGTH: 100,
  INTERESTING_TAGS_MIN_LENGTH: 10,
  INTERESTING_TAGS_MAX_LENGTH: 100,
};

export { StepsValidationRule };
