const UserValidationRule = {
  FIRST_NAME_MIN_LENGTH: 2,
  FIRST_NAME_MAX_LENGTH: 30,
  LAST_NAME_MIN_LENGTH: 2,
  LAST_NAME_MAX_LENGTH: 30,
  PASSWORD_MIN_LENGTH: 3,
  PASSWORD_MAX_LENGTH: 30,
};

export { UserValidationRule };
