enum ActionType {
  GET_ALL_CAREER_JOURNEYS = 'GET_ALL_CAREER_JOURNEYS',
  CREATE_CAREER_JOURNEY = 'CREATE_CAREER_JOURNEY',
  UPDATE_CAREER_JOURNEY = 'UPDATE_CAREER_JOURNEY',
  REMOVE_CAREER_JOURNEY = 'REMOVE_CAREER_JOURNEY',
}

export { ActionType };
